maanaim/config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio'

  get 'paginas/ajuda'
  
  get 'paginas/lista_eventos'
  
  root 'paginas#inicio'
  
  scope '/admin' do
    resources :users
  end
  
  scope "/:evento" do
    resources :pagamentos
    resources :pedidos
  end
  
  get '/eventos/:id/relatorio', to: 'eventos#relatorio', as: 'relatorio_evento'
  
  
  resources :produto_pedidos
  resources :produtos
  resources :eventos
  resources :pessoas
  resources :tipo_eventos
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

maanaim/app/models/pessoa.rb
class Pessoa < ApplicationRecord
  has_many :eventos_pessoas
  
  def self.search(search)
    if search
      where('nome LIKE ?', "%#{search}%")
    else
      where('nome LIKE ?', "%%")
    end
  end
end

maanaim/app/controllers/pessoas_controller.rb
class PessoasController < OrdenavelController
  before_action :set_pessoa, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to :pessoas, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to :pessoas, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:cpf, :nome, :sexo, :dtNasc, :logradouro, :cep, :bairro, :email, :telefone, :ativo)
    end
    
end

maanaim/app/views/pessoas/_form.html.erb
<%= simple_form_for(@pessoa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :cpf %>
    <%= f.input :nome %>
    <%= f.input :sexo %>
    <%= f.input :dtNasc, as: :string, input_html: { type: 'date'} %>
    <%= f.input :logradouro %>
    <%= f.input :cep %>
    <%= f.input :bairro %>
    <%= f.input :email %>
    <%= f.input :telefone %>
    <%= f.input :ativo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

maanaim/app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

maanaim/app/views/pessoas/index.html.erb
<table class="table">
<thead>
  <tr>
    <th>Cpf</th>
    <th>Nome</th>
    <th>Sexo</th>
    <th>Data de nascimento</th>
    <th>Logradouro</th>
    <th>Cep</th>
    <th>Bairro</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Ativo</th>
    <th colspan="2"></th>
  </tr>
</thead>

<tbody>
  <% @pessoas.each do |pessoa| %>
    <tr>
      <td><%= pessoa.cpf %></td>
      <td><%= pessoa.nome %></td>
      <td><%= pessoa.sexo %></td>
      <td><%= pessoa.dtNasc %></td>
      <td><%= pessoa.logradouro %></td>
      <td><%= pessoa.cep %></td>
      <td><%= pessoa.bairro %></td>
      <td><%= pessoa.email %></td>
      <td><%= pessoa.telefone %></td>
      <td><%= pessoa.ativo %></td>
      <td><%= link_to 'Edit', edit_pessoa_path(pessoa), remote: true %></td>
      <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

maanaim/app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

maanaim/app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpf:</strong>
  <%= @pessoa.cpf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @pessoa.sexo %>
</p>

<p>
  <strong>Dtnasc:</strong>
  <%= @pessoa.dtNasc %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @pessoa.logradouro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @pessoa.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @pessoa.bairro %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @pessoa.telefone %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @pessoa.ativo %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>