maanaim/config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio'

  get 'paginas/ajuda'
  
  get 'paginas/lista_eventos'
  
  root 'paginas#inicio'
  
  scope '/admin' do
    resources :users
  end
  
  scope "/:evento" do
    resources :pagamentos
    resources :pedidos
  end
  
  get '/eventos/:id/relatorio', to: 'eventos#relatorio', as: 'relatorio_evento'
  
  
  resources :produto_pedidos
  resources :produtos
  resources :eventos
  resources :pessoas
  resources :tipo_eventos
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

maanaim/app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tipo_evento
  has_many :conta_eventos, dependent: :destroy
  has_many :pedidos, through: :conta_eventos
  has_many :pagamentos, through: :conta_eventos
  has_many :pessoas, through: :conta_eventos
  
  def self.search(search)
    if search
      where('nome LIKE ?', "%#{search}%")
    else
      where('true')
    end
  end
  
  attr_reader :total_vendas, :total_recebido, :total_descontos, :total_pendente
  
  def gerar_relatorio
    @total_vendas = 0.0
    self.pedidos.each do |pdd| 
      @total_vendas += pdd.total
    end
    
    @total_recebido = 0.0
    @total_descontos = 0.0
    @total_pendente = 0.0
    
    self.pagamentos.each do |pg|
      @total_recebido += pg.valor
      @total_descontos += pg.desconto
    end
    
    @total_pendente =(@total_recebido + @total_descontos) - @total_vendas
    
  end
  
end

maanaim/app/controllers/eventos_controller.rb
class EventosController < OrdenavelController
  before_action :set_evento, only: [:show, :edit, :update, :destroy, :relatorio]
  before_action :authenticate_user!

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end
  
  def relatorio
    @evento.gerar_relatorio
    render layout: false
  end


  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to :eventos, notice: 'Evento was successfully created.' }
        format.json { redirect_to :eventos, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to :eventos, notice: 'Evento was successfully updated.' }
        format.json { redirect_to :eventos, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:quantidade_de_vagas, :data_de_inicio, :data_de_fim,:nome, :tipo_evento_id,pessoa_ids:[])
      
    end
    
end

maanaim/app/views/eventos/_form.html.erb
<%= simple_form_for(@evento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :quantidade_de_vagas %>
    <%= f.input :data_de_inicio, as: :string, input_html: { type: 'date'} %>
    <%= f.input :data_de_fim, as: :string, input_html: { type: 'date'} %>
    <%= f.association :tipo_evento, label_method: :nome %>
    <%= f.association :pessoas,label_method: :nome,collection: Pessoa.where(ativo: true).order(:nome) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

maanaim/app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

maanaim/app/views/eventos/index.html.erb
<table class="table">
<thead>
  <tr>
    <th><%= sortable "nome" %></th>
    <th><%= sortable "quantidade_de_vagas" %></th>
    <th><%= sortable "data_de_inicio" %></th>
    <th><%= sortable "data_de_fim" %></th>
    <th><%= sortable "tipo_evento" %></th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @eventos.each do |evento| %>
    <tr>
      <td><%= evento.nome %></td>
      <td><%= evento.quantidade_de_vagas %></td>
      <td><%= evento.data_de_inicio %></td>
      <td><%= evento.data_de_fim %></td>
      <td><%= evento.tipo_evento.nome %></td>
      <td><%= link_to 'Editar', edit_evento_path(evento), remote: true %></td>
      <td><%= link_to 'Gerar relatório', relatorio_evento_path(evento) %></td>
      <td><%= link_to 'Apagar', evento, method: :delete, data: { confirm: 'Os dados serão excluídos permanentemente, deseja continuar?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

maanaim/app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

maanaim/app/views/eventos/relatorio.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.github.io/templates/blank/theme.css" type="text/css"> </head>

<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img class="img-fluid d-block" src="<%= image_path 'maanain-01' %>"> </div>
        <div class="col-md-6 align-self-center">
          <h1 class="">Relatório de evento Maanaim
            <br>Evento: <%= @evento.nome %></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blockquote">
            <p>Resumo</p>
            <ul class="list-group">
              <li class="list-group-item">Total de vendas: &nbsp;<%= number_to_currency(@evento.total_vendas, :separator => ",", :delimiter => ".", :unit => "R$") %></li>
              <li class="list-group-item">Total recebido: &nbsp;<%= number_to_currency(@evento.total_recebido, :separator => ",", :delimiter => ".", :unit => "R$") %></li>
              <li class="list-group-item">Total de descontos: &nbsp;<%= number_to_currency(@evento.total_descontos, :separator => ",", :delimiter => ".", :unit => "R$") %></li>
              <li class="list-group-item">Total pendente: &nbsp;<%= number_to_currency(@evento.total_pendente, :separator => ",", :delimiter => ".", :unit => "R$") %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blockquote">
            <p>Vendas por pessoa</p>
            <table class="table">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Valor comprado</th>
                  <th>Valor pago</th>
                  <th>Descontos</th>
                  <th>Saldo devedor</th>
                </tr>
              </thead>
              <tbody>
                <% @evento.conta_eventos.each do |conta| %>
                <tr>
                  <td><%= conta.nome %></td>
                  <td><%= number_to_currency(conta.comprado, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
                  <td><%= number_to_currency(conta.pago, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
                  <td><%= number_to_currency(conta.desconto, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
                  <td><%= number_to_currency(conta.saldo, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

maanaim/app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantidade de vagas:</strong>
  <%= @evento.quantidade_de_vagas %>
</p>

<p>
  <strong>Data de inicio:</strong>
  <%= @evento.data_de_inicio %>
</p>

<p>
  <strong>Data de fim:</strong>
  <%= @evento.data_de_fim %>
</p>

<p>
  <strong>Tipo evento:</strong>
  <%= @evento.tipo_evento %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>