maanaim/config/routes.rb
Rails.application.routes.draw do
  get 'paginas/inicio'

  get 'paginas/ajuda'
  
  get 'paginas/lista_eventos'
  
  root 'paginas#inicio'
  
  scope '/admin' do
    resources :users
  end
  
  scope "/:evento" do
    resources :pagamentos
    resources :pedidos
  end
  
  get '/eventos/:id/relatorio', to: 'eventos#relatorio', as: 'relatorio_evento'
  
  
  resources :produto_pedidos
  resources :produtos
  resources :eventos
  resources :pessoas
  resources :tipo_eventos
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

maanaim/app/models/produto_pedido.rb
class ProdutoPedido < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
 
end

maanaim/app/controllers/produto_pedidos_controller.rb
class ProdutoPedidosController < ApplicationController
  before_action :set_produto_pedido, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /produto_pedidos
  # GET /produto_pedidos.json
  def index
    @produto_pedidos = ProdutoPedido.all
  end

  # GET /produto_pedidos/1
  # GET /produto_pedidos/1.json
  def show
  end

  # GET /produto_pedidos/new
  def new
    @produto_pedido = ProdutoPedido.new
  end

  # GET /produto_pedidos/1/edit
  def edit
  end

  # POST /produto_pedidos
  # POST /produto_pedidos.json
  def create
    produto_pedido = ProdutoPedido.new(produto_pedido_params)
    if produto_pedido.save
      
      @pedido = produto_pedido.pedido
      @produto_pedido = ProdutoPedido.new(pedido: @pedido)
      @total = 0.0
      @pedido.produto_pedidos.each { |pp| @total += pp.produto.preco*pp.quantidade }
      render 'create.js'
    else
      render 'create.js'
    end
  end

  # PATCH/PUT /produto_pedidos/1
  # PATCH/PUT /produto_pedidos/1.json
  def update
    respond_to do |format|
      if @produto_pedido.update(produto_pedido_params)
        format.html { redirect_to @produto_pedido, notice: 'Produto pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto_pedido }
      else
        format.html { render :edit }
        format.json { render json: @produto_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produto_pedidos/1
  # DELETE /produto_pedidos/1.json
  def destroy
    @pedido = @produto_pedido.pedido
    @produto_pedido.destroy
    @produto_pedido = ProdutoPedido.new(pedido: @pedido)
    @total = 0.0
    @pedido.produto_pedidos.each { |pp| @total += pp.produto.preco*pp.quantidade }
    render 'destroy.js'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto_pedido
      @produto_pedido = ProdutoPedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_pedido_params
      params.require(:produto_pedido).permit(:pedido_id, :produto_id, :quantidade)
    end
end

maanaim/app/views/produto_pedidos/_form.html.erb
<%= simple_form_for(@produto_pedido, remote: true, html: {class: "form-inline"}) do |f| %>
  <%= f.error_notification %>

    <%= f.association :pedido, :as => :hidden, value_method: :id%>
    <%= f.input :quantidade,  wrapper_html: {class: "form-group w-25"}, input_html: {class: 'form-control w-50'} %>
    <%= f.association :produto,collection: Produto.where(ativo: true).order(:nome), label_method: :nome, wrapper_html: {class: "form-group w-50"}, input_html: {class: 'form-control w-75'} %>

    <%= f.submit 'Adicionar', class:"btn btn-primary w-25" %>
<% end %>
<%= render 'produto_pedidos/index' %>

maanaim/app/views/produto_pedidos/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Qtde</th>
      <th>Produto</th>
      <th>Valor Unid.</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody style="height: 120px; overflow-y: auto;">
    <% @pedido.produto_pedidos.each do |produto_pedido| %>
      <tr>
        <td><%= produto_pedido.quantidade %></td>
        <td><%= produto_pedido.produto.nome %></td>
        <td><%= number_to_currency(produto_pedido.produto.preco, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
        <td><%= number_to_currency(produto_pedido.produto.preco*produto_pedido.quantidade, :separator => ",", :delimiter => ".", :unit => "R$") %></td>
        <td><%= link_to 'Remover', produto_pedido, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

maanaim/app/views/produto_pedidos/_modal.html.erb
  <div class="modal" id="myModal" data-toggle="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal" type="button" aria-hidden="true" data-target="#myModal">×</button>
          <h4 class="modal-title"><%= titulo %></h4>
        </div>
        <div class="modal-body">
          <%= form %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

maanaim/app/views/produto_pedidos/create.js.erb
value =  "<%= escape_javascript (render 'produto_pedidos/form') %>"
$("#myContent").html(value);
$("#total").html("<%= number_to_currency(@total, :separator => ",", :delimiter => ".", :unit => "R$") %>");

maanaim/app/views/produto_pedidos/destroy.js.erb
value =  "<%= escape_javascript (render 'produto_pedidos/form') %>"
$("#myContent").html(value);
$("#total").html("<%= number_to_currency(@total, :separator => ",", :delimiter => ".", :unit => "R$") %>");

maanaim/app/views/produto_pedidos/edit.html.erb
<h1>Editing Produto Pedido</h1>

<%= render 'form', produto_pedido: @produto_pedido %>

<%= link_to 'Show', @produto_pedido %> |
<%= link_to 'Back', produto_pedidos_path %>

maanaim/app/views/produto_pedidos/new.html.erb
<h1>New Produto Pedido</h1>

<%= render 'form', produto_pedido: @produto_pedido %>

<%= link_to 'Back', produto_pedidos_path %>

maanaim/app/views/produto_pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @produto_pedido.pedido %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @produto_pedido.produto %>
</p>

<%= link_to 'Edit', edit_produto_pedido_path(@produto_pedido) %> |
<%= link_to 'Back', produto_pedidos_path %>